name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  cloud_firestore: 3.2.1
  firebase_auth: 3.4.1
  firebase_core: 1.19.1
  firebase_storage: 10.3.1
  image_picker: ^0.8.5+3
  convex_bottom_bar: ^3.0.0
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  syncfusion_flutter_datepicker: ^20.2.40
  intl: ^0.17.0
  flutter: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

